### PR TITLE
Simplify mapping between Windows and TZDB time zone IDs

### LINKED ISSUE #274: Simplify Windows to/from IANA conversion methods
```
What situation does this request make simpler?
Since Noda Time contains IANA, Windows, and CLDR data, it can be used to 
convert BCL time zones to or from TZDB time zones.  The data is exposed in the 
API, but sensible conversion methods aren't included.  This could be more 
convenient, such as illustrated here:
http://stackoverflow.com/a/17348822/634824

Can you provide a straw-man example of what you'd want the API to look
like?

string bclZoneId = 
TzdbDateTimeZoneSource.Default.WindowsMapping.TranslateToBcl(tzdbZoneId);

string tzdbZoneId = 
TzdbDateTimeZoneSource.Default.WindowsMapping.TranslateToTzdb(bclZoneId);


We could also consider (in addition) a new method to DateTimeZone with the 
signature:

public DateTimeZone TranslateFor(IDateTimeZoneProvider provider)

Which would give some convenience for those not used to calling into a the 
TzdbDateTimeSource, for example:

DateTimeZone bclZone = 
DateTimeZoneProviders.Tzdb[tzdbZoneId].TranslateFor(DateTimeZoneProviders.Bcl);

DateTimeZone tzdbZone = 
DateTimeZoneProviders.Bcl[bclZoneId].TranslateFor(DateTimeZoneProviders.Tzdb);




```

Original issue reported on code.google.com by `mj1856` on 26 Mar 2014 at 6:08

### PR DESCRIPTION
**Pull request by jskeet**
Fixes #274.

I'd be open to the idea of adding convenience methods to TzdbDateTimeZoneSource as well, that just pass through to WindowsZones, if that were considered useful.

(Matt, are you happy to review? This was your original issue, many years ago :)

### CODE REVIEW

**Comment by jskeet** [comment]
Note that this doesn't include anything for TZDB aliases, as described in #827.

**Comment by jskeet** [comment]
If we wanted to handle TZDB aliases, it would probably make sense to *only* put the methods on `TzdbDateTimeZoneSource`, and always return canonical TZDB IDs. Maybe :)

**Comment by mj1856** [comment]
I'll take a look and get back to you.  Thanks.

**Comment by jskeet** [comment]
@mj1856: Thanks. The more I think about it, it more I suspect that just putting methods on TzdbDateTimeZoneSource is the way forward, to avoid the mess of having to think about CLDR-canonical vs TZDB-canonical etc.

**Comment by jskeet** [comment]
I'm going to start a new branch for the "TzdbDateTimeZoneSource methods only" version.

**Comment by jskeet** [comment]
Abandoning this in favour of #1393

**Pull request closed without merging**
