### PR TITLE
Feature/#385 plus mintues to zoned date time

### PR DESCRIPTION
**Pull request by jackthorley**
In relation to [Feature 385](https://github.com/nodatime/nodatime/issues/385). 

No breaking change to current functionality, purely additive. Please inform me if there are any test cases missing or additional modifications.

Thanks.

### CODE REVIEW

**Comment by jskeet** [comment]
Thanks for this.

I'd been trying to avoid expanding these APIs too much - I wonder whether they might be better as extension methods? Hmm. I can see the usefulness of it... it's always a dilemma.

Also, there are a few changes which are just adding blank lines - could you remove those and rebase so that the commits are just code changes? Feel free to rebase into a single commit and force push (which will avoid seeing the reordering in a separate commit, making the whole thing more cohesive).

Next, there are some doc comments talking about milliseconds when it means seconds or nanoseconds - could you fix them please?

Finally, is there any reason you didn't include PlusTicks? While it's not terribly useful outside the Windows world, I can imagine it being handy for anyone doing a direct conversion of BCL code. If there aren't 

(There are various empty "returns" XML comment elements, but there are in the original too, so don't worry - I'll fix all of those in one go.)

**Comment by jskeet** [comment]
Hi Jack,

Can I check the status of this PR? If you don't have the time to make the changes I talked about, I'd be happy to look at doing so myself. (Not sure what that would consist of in git terms, but I'm sure I'd work it out.)

**Comment by jackthorley** [comment]
Hi Jon,

Apologies for not assigning much time to this. I initially had some issues with the Travis pipeline, however after upgrading my branch to include latest master changes these seem to have been resolved. It was quite possibly an intermittent issue with Travis.

I've made the top level changes to the code, mainly formatting, as requested. I haven't taken much thought around over-bloating the library the APIs; however I feel you're correct, a refactor to extension methods is probably a responsible approach in the long term.

**Comment by jskeet** [comment]
Yes, the Travis pipeline was broken while we were using mono:nightly. I'll have another look and merge in tomorrow if I can - we can always move them to be extension methods shortly before the release.

Thanks again for your contribution!

**Pull request merged**
