### PR TITLE
Upgrade from Foundation 4 to Foundation 5

### LINKED ISSUE #711: Update our web site dependency packages
We're using old versions of Zepto, jQuery, Foundation etc - and almost certainly not using them in a way that's idiomatic for ASP.NET Core. (We should just be able to list them somewhere, I suspect....)

### PR DESCRIPTION
**Pull request by malcolmr**
Upgrade the website from Foundation 4.something to 5.5.3.

This is mostly straightforward. There are a few minor differences:

- The navbar has slightly different padding for the menu items, and styling for the Install button (and the dividers look a little different).
- The `<code>` font isn't bold, and has a slight background (see e.g. the type names and links on http://nodatime.org/2.0.x/userguide/type-choices). I think this actually looks better.
- The side-bar menu in e.g. the user guide no longer has clickable section headers (Introduction, Core, Text, etc). These didn't do anything when clicked anyway.
- Padding and margins are slightly different throughout, though not by much.
- The site might not work in IE7/8 (that's <0.05% of our users).

Fixes #711.

### CODE REVIEW

**Comment by malcolmr** [comment]
(Probably want to resolve #794 before pushing this live, btw.)

**Comment by jskeet** [comment]
Given the comment about caching, do we want to try to build that into this PR? I haven't looked at caching (or cache-busting) in ASP.NET Core at all yet.

**Comment by malcolmr** [comment]
I think the cache-busting (we already have caching implicitly, albeit not well-configured caching) is orthogonal to this, but we should probably wait to have a good solution before submitting this (or any large-scale change, really).

(I think the solution is going to be pretty easy, so that's the next thing I'm planning to look at.)

**Comment by jskeet** [comment]
The simplest way of me testing this is probably just to merge it, pull and regenerate the website, then test it locally. I'll only push if it looks okay :)

**Comment by jskeet** [comment]
Tested, and it looks fine. Pushing to nodatime.org.

**Pull request merged**
