### PR TITLE
Upgrade targets to include .NET 6

### PR DESCRIPTION
**Pull request by jskeet**
This is along the way to #1635. It's a bit of a shame that we have to go back to multiple targets, but there may well be other things we want to be able to do with .NET 6 as well, over time.

### CODE REVIEW

**Comment by jskeet** [comment]
@malcolmr: Removed you as a reviewer for now, as I'll need to work out what's failing on Linux.
(A lot has changed in .NET 6 in terms of handling of time zone IDs, so that's probably what it's about.)

**Comment by silkfire** [comment]
Could we remove the dependency on `System.Runtime.CompilerServices.Unsafe` for .NET 6 as it's included in the framework since .NET Core 3.1?

**Comment by jskeet** [comment]
@silkfire: Yes, quite possibly. (It may automatically be removed - I'm not sure.)

The bigger problem with .NET 6 is around time zones - I need to find a solid few hours to work on that, and I'm not sure that'll be soon :(

**Comment by silkfire** [comment]
Take your time, literally :)

**Comment by jskeet** [comment]
This PR is now basically about fixing the time zone issues for .NET 6 - #1675 already upgraded to use the .NET 6.0 SDK.

**Pull request merged**
