### PR TITLE
Convert Duration to use BigInteger instead of decimal

### PR DESCRIPTION
**Pull request by jskeet**
Fixes issue #447.
(Still need to check performance, although relatively few operations will be affected.)

### CODE REVIEW

**Comment by jskeet** [comment]
Minor data point: calling Duration.To{BigInteger/Decimal}Nanoseconds(), 10 million times, on a duration of 100 days and 5 hours:

- Decimal: ~0.6s
- BigInteger: ~1.9s

(For reference, ToInt64Nanoseconds takes about 0.05s. So whenever it's reasonable to use that - if the duration would never be more than +/- 292 years unless there are other problems - that's a good thing.)

So it's a significant (3x) but not ridiculous performance regression.
If we don't need to do this too often, that's probably okay.

Next step: working out how often we do this internally.

**Comment by jskeet** [comment]
Okay, so, analysis:

- ToBigIntegerNanoseconds is called by:
  - Multiplication where either the duration operand is negative, or the result ends up being larger than +/-292 years
  - Division where the duration operand is larger than +/- 292 years

- FromBigIntegerNanoseconds is called by:
  - The above operations (BigInteger is just an intermediate format for computation)
  - Duration text parsing (relatively rare)

I think we should optimize multiplication for negative durations as well, but at that point this performance sacrifice is probably good enough.

**Comment by jskeet** [comment]
Unfortunately with the state of our benchmarks at the moment I can't *verify* that this degrade performance significantly, but I don't believe it will.

This should be a simpler basis for implementing issue #404.

**Comment by malcolmr** [comment]
LGTM

**Pull request merged**
