### PR TITLE
Update LocalTime.cs

### PR DESCRIPTION
**Pull request by PCavan**
Made LocalTime.FromNanosecondsSinceMidnight public with corrected documentation

### CODE REVIEW

**Comment by jskeet** [comment]
(Will merge on green.)

**Comment by PCavan** [comment]
The tests appear to have passed, but the AppVeyor report-build failed for some reason.

**Comment by jskeet** [comment]
Will check it when I get a chance, but that may be tomorrow.

**Comment by jskeet** [comment]
Looks like it's the code coverage part - which I thought was working again now. Will need to investigate that separately.

**Pull request merged**
