### PR TITLE
update format info to use C# 7 patterns

### PR DESCRIPTION
**Pull request by BillWagner**
This is much clearer with C# 7 pattern matching expressions.

### CODE REVIEW

**Comment by BillWagner** [comment]
@jskeet The Travis CI build is failing because it looks like the version you're using for .NET Core is still running the 6.0 compiler. Is it in your plans to update this, or should I close this PR until later?

**Comment by jskeet** [comment]
Feel free to just leave the PR for now - I'm going to update to the new SDK when VS 2017 is fully baked (so I can update to csproj).

Thanks for the PR though - and of course, feel free to refer to it as a real-world example of pattern matching :)

**Comment by jskeet** [comment]
Now that we can only be opened in VS2017, I need to work out how to get C# 7 support (if anything is actually required...)

**Comment by jskeet** [comment]
Looks like nothing needs to be done, so I should be able to merge this...

**Comment by jskeet** [comment]
Closing in favour of #698.

**Pull request closed without merging**
