### PR TITLE
Fix Travis build using the latest .NET Core 3.0 SDK

### PR DESCRIPTION
**Pull request by jskeet**
(We may well want to update to .NET Core 3.1, but that can come later.)

### CODE REVIEW

**Comment by jskeet** [comment]
Not merging this now, as AppVeyor doesn't support 3.1 yet, and Travis is basically okay now.

**Comment by Youssef1313** [comment]
I think 3.1.100 is supported by appveyor, you may use it until 3.1.101 is supported.

**Comment by jskeet** [comment]
I could do that - but I'd rather just wait another week, instead of shifting things twice :)

**Comment by jskeet** [comment]
This is now obsolete.

**Pull request closed without merging**
