### PR TITLE
Added support for custom pattern on a text serialization + tests

### PR DESCRIPTION
**Pull request by apavelm**
Modification that allows to define custom patterns using built-in type converters for string to noda deserialization

### CODE REVIEW

**Comment by apavelm** [comment]
@jskeet Hi there! Xmas is coming, what about the fix/extension? :-)

**Comment by jskeet** [comment]
If you could gift me another couple of hours a day, that would be great. Otherwise, I'm afraid it'll have to wait a bit.

**Comment by jskeet** [comment]
I *have* had enough time to look very briefly though - and I'm not keen. This introduces more global mutable state, which is something I'm always *very* nervous of. As I said on #1765, it seems to me like the expected way to specify custom type converters is to use the `[TypeConverter]` attribute on the properties.

If you can provide examples of a global TypeConverter re-configuration scheme like you're proposing here in other significant projects (ideally in .NET itself) then that would be a lot more compelling. But I really, really don't want to introduce global mutable state just so that you can avoid specifying TypeConverter attributes.

**Comment by apavelm** [comment]
If I could extend a day for a couple of hours... Unfortunately, I can't

The proposed way looks to me the most optimal considering the needs, but personally I have no objections, if you could suggest another way how to reach the goal. 
Let me remind from what all the discussions began  [110](https://github.com/nodatime/nodatime.serialization/issues/110)
It started around nodatime.serialization for AspNet.Core projects. As was identified, deserialization using custom format pattern works fine in POST requests, but doesn't work in GET requests, because for get requests it uses "string -> nodetime" converter. Currently, there are no known options how to extend it and to make it work with custom pattern formats.
If you could suggest any workable alternative, it would be good.

The suggestion to use string as a request parameter type instead of NodaTime models in GET requests and deserialize them manually - is not serious, and it also will require introducing additional static variable (jsonSerializerSettings) that will be used only for these purposes. To me, it looks clear that such a thing should be hidden inside the serialization library as an "operator" of all converters.
And again, if you prefer to go another way (discussed also), by exposing some internals (making some fields public) it will also solve the problem.

**Comment by jskeet** [comment]
As I've said before, I think the most appropriate option is for you to decorate your properties with `[TypeConverter]`. You've said you don't like that, and that's fine - but I've said *I* don't like adding more mutable global state and a non-idiomatic type converter configuration mechanism.

I'd be happy to make `TypeConverterBase<T>` public (possibly renaming it in the process) to make it *easier* to add the attributes, but that's very different from introducing global state. (And even that is unlikely to get into a new release very soon - I've still got some other features/fixes to work on before I do another release, and unexpected personal and work time pressures have prevented me from getting to those yet.)

**Pull request closed without merging**
