### PR TITLE
First pass at an ISO-only annual date type.

### PR DESCRIPTION
**Pull request by jskeet**
(Looks a bit simple at the moment... not sure what else is needed.)

### CODE REVIEW

**Comment by malcolmr** [comment]
I assume this is the MonthDay suggestion from #317?

Any reason not to go for `MonthDay` as the type name, especially given that's what `java.time` uses?

**Comment by jskeet** [comment]
Reason for not using MonthDay was user feedback from idg10 and MenoData. Personally I'd still like MonthDay, but I'm okay with AnnualDate too... although I wonder whether we could have MonthDay implement an IAnnualDate interface, where other implementions could be for things like "Easter".

I'd be happy to work out the functionality and get it submitted with *any* name, and then revisit before release.

**Comment by jskeet** [comment]
I *think* I've fixed everything other than the name and the text parsing, both of which need further discussion. I'll squash the commits before merging, after they've been reviewed.

**Comment by malcolmr** [comment]
LGTM as-is. Let's discuss the name separately.

Parsing we can always add later, so I don't think is a blocker for anything.

**Pull request merged**
