### PR TITLE
Corrected typo.

### PR DESCRIPTION
**Pull request by cjdsellers**

### CODE REVIEW

**Comment by jskeet** [comment]
I merged the first commit a while ago - could you rebase so that this shows just one commit, just to make sure I'm not delusional?

**Comment by cjdsellers** [comment]
My apologies Jon, I should have squashed them into the one commit... not sure how to proceed. Its another very small typo.

**Comment by jskeet** [comment]
Not a problem - just rebase your branch to master, force push it, and this PR should end up with one commit. Or I could just fix the typo manually if you don't care about the commit history attribution :)

**Comment by cjdsellers** [comment]
I think I'll let you have that one Jon ;)

In the mean time I'll do some more study on Git!

**Comment by jskeet** [comment]
Righto - thanks for spotting these though :)

**Pull request closed without merging**
