### PR TITLE
Add snippets for Offset type

### PR DESCRIPTION
**Pull request by carlosschults**

### CODE REVIEW

**Comment by jskeet** [comment]
I'm at a conference at the moment so can't review this right now - I'll try next week, but I've got another conference then.

More importantly, snippet processing is currently broken. It was relying on some (old) Roslyn betas which have now been removed from MyGet - I'm trying to get it working with GA versions, but I've failed so far.

**Comment by carlosschults** [comment]
No hurry Jon :)

By the way, is there any way I could help in regards to the snippets problem?

**Comment by jskeet** [comment]
The snippets problem is a matter of successfully loading a project into Roslyn and then compiling it. I've gone a fair way in terms of creating a complete example to show the Roslyn team (either as a bug report or for workarounds) but need a bit more time to finish it off...

**Comment by jskeet** [comment]
(Test failure has nothing to do with this change; I'll look at it when I get a chance.)

**Comment by jskeet** [comment]
Looks like snippets are still currently working on the build machine, presumably as the relevant Roslyn nuget packages are cached. Phew. (Still need to tidy that up, of course...)

**Pull request merged**
