### PR TITLE
Add snippet for Day, DayOfWeek and DayOfYear

### PR DESCRIPTION
**Pull request by neiesc**
Add snippet for Day, DayOfWeek and DayOfYear.
Ref: #918

### CODE REVIEW

**Review by jskeet — APPROVED** [review]

**Comment by jskeet** [comment]
Thanks! Merging now.

**Comment by neiesc** [comment]
@jskeet Please add support to hacktoberfest

https://hacktoberfest.digitalocean.com
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by jskeet** [comment]
@neiesc: I would really rather not. My experience of previous Hacktoberfest is that it basically attracts a lot of spam PRs, making extra work for maintainers with no benefit for the project. This PR was fine and added value, and I'd be happy to somehow include *that* in Hacktoberfest if it can be done on a per-PR basis, but I don't want to sign the project up globally.

**Comment by neiesc** [comment]
> @neiesc: I would really rather not. My experience of previous Hacktoberfest is that it basically attracts a lot of spam PRs, making extra work for maintainers with no benefit for the project. This PR was fine and added value, and I'd be happy to somehow include _that_ in Hacktoberfest if it can be done on a per-PR basis, but I don't want to sign the project up globally.

Yes, I understand your position as a mateneedor, I would also do the same. I want to continue contributing to NodaTime even after the hacktoberfest.

But I think that just by adding "hacktoberfest-accepted" in PR it already becomes readable, I think, but if you don't want it all right, I'm not just for the shirt but for the open source.

**Comment by jskeet** [comment]
Done. Fingers crossed that will work...

**Pull request merged**
